apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c8agf0ijh-nodejs 
  janus-idp.io/tekton: c8agf0ijh-nodejs
  backstage.io/kubernetes-id: c8agf0ijh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c8agf0ijh-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml