apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: c8agf0ijh-nodejs-gitops
  description: This is GitOps manifest for c8agf0ijh-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=c8agf0ijh-nodejs
    backstage.io/kubernetes-id: c8agf0ijh-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: c8agf0ijh-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:c8agf0ijh-nodejs
